savePrefix: ""
autoInstallPeers: false
strictPeerDependencies: true
overrides:
  vinxi: "$vinxi"
ignoredBuiltDependencies:
  - "@parcel/watcher"
  - "@tailwindcss/oxide"
  - esbuild
onlyBuiltDependencies:
  - sharp
  - workerd
